/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    AppLink: typeof import('./components/AppLink.vue')['default']
    AppPage: typeof import('./components/AppPage.vue')['default']
    AppPreloader: typeof import('./components/AppPreloader.vue')['default']
    IconEditPencil: typeof import('./components/icons/IconEditPencil.vue')['default']
    IconPlusRound: typeof import('./components/icons/IconPlusRound.vue')['default']
    IndexPage: typeof import('./pages/IndexPage.vue')['default']
    PagesPage: typeof import('./pages/PagesPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TonConnectButton: typeof import('./tonconnect/TonConnectButton.vue')['default']
  }
}
