/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    AppPage: typeof import('./components/AppPage.vue')['default']
    AuthButton: typeof import('./components/AuthButton.vue')['default']
    IndexPage: typeof import('./pages/IndexPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TonConnectButton: typeof import('./tonconnect/TonConnectButton.vue')['default']
  }
}
